app/assets/javascripts/user.coffee, app/assets/stylesheets/user.scss, app/controllers/user_controller.rb, app/helpers/user_helper.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/user/edit.html.haml, spec/controllers/user_controller_spec.rb, spec/helpers/user_helper_spec.rb
ログアウトページのhtml,cssファイルを作成
#Why
ログアウトページを実装するため
=> [WIP]Logout page

README.md, db/migrate/20200114052218_add_column_users.rb, db/schema.rb
Reverts YoSi9N/freemarket_sample_66a_nagoya#9
=> Revert "[WIP]ソーシャルログイン実装にあたって、DBを修正"

app/assets/stylesheets/profile.scss, app/controllers/items_controller.rb, app/controllers/users_controller.rb, app/views/users/profile_show.html.haml, config/routes.rb
#WHAT
ユーザープロフィールページのビュー完成
usersテーブルからnicknameとself_introductionを取り出して表示
上記を編集、入力して変更するボタンを押すとDB内の情報を書き換えて再びプロフィールを表示
#WHY
ニックネームの編集を可能にするため
自己紹介文の編集を可能にするため
=> [WIP]プロフィール入力ページの実装

app/assets/stylesheets/users.scss, app/views/users/new.html.haml
ログインするためのビュー作成
メール、google、facebookそれぞれでログインできるようにするため
=> 新規会員ページビュー作成

app/assets/stylesheets/items.scss, app/assets/stylesheets/items_show.scss, app/controllers/items_controller.rb, app/views/items/index.html.haml, app/views/items/new.html.haml, app/views/items/show.html.haml, config/routes.rb
#WHAT
商品詳細ページ、出品ページのビューの作成
#WHY
商品を出品してもらうため。
商品の詳細を確認するため。
=> [WIP]View items new, show

app/assets/stylesheets/items.scss, app/views/items/new.html.haml
出品ページのビューの作成
出品ページの見た目をよくするため。
=> [WIP]create items_new view

app/assets/stylesheets/users.scss, app/views/devise/registrations/create_address_user.html.haml, app/views/devise/registrations/new.html.haml, app/views/devise/registrations/new_address_user.html.haml, app/views/users/new.html.haml
ユーザー情報の登録画面
登録完了画面を作成
ユーザーからの情報を入力させられるページが必要なため
=> [WIP]ユーザー情報登録画面作成

app/assets/stylesheets/credit.scss, app/views/users/credit.html.haml
クレジットカード情報登録画面の作成
登録したクレジット情報で商品購入ができるようにするため
=> credit-view

README.md, db/migrate/20200110125250_create_items.rb
=> sprint_review_2_1

app/views/devise/registrations/new.html.haml, app/views/devise/registrations/new_address_user.html.haml, app/views/users/_policy.html.haml, app/views/users/new.html.haml
ユーザー登録ページのフッタを部分テンプレートに変更
記述を見やすくするするため
=> [WIP]footer 部分テンプレート

app/assets/javascripts/items_image_new.js, app/assets/stylesheets/items.scss, app/views/items/new.html.haml
image投稿際のビュー崩れの修正
imageの編集、削除機能の追加
imageの編集、削除機能を追加することによりわざわざリロードしなくてもimageを選択することができる。
=> [WIP]出品機能のimageの動的表現

app/assets/stylesheets/users.scss, app/views/users/new.html.haml
=> 新規ログイン画面ビューの修正

app/views/items/buy_confirmation.html.haml, app/views/users/_policy.html.haml
=> フッターの部分テンプレートを適応

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/login_page.scss, app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/views/devise/sessions/new.html.haml, config/initializers/recaptcha.rb
https://gyazo.com/ff0d6e405f10da397919f8502cc52999
=> ログインページの修正とリキャプチャ機能の追加

app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb
#WHAT
1.新規ユーザー登録時に入力項目がnilになってしまう
2.ソーシャルログイン時も同様
以上の不具合を解消
#WHY
ログイン機能の回復
#HOW
recaptcha(ロボット判定)導入時に記入した記述の一部を削除
※導入時に複数のブログを参照したが、別の複数のサイトでの導入方法を参考にして不必要な記述を削除
=> ユーザー登録時の不具合を解消

app/assets/javascripts/category.js, app/controllers/items_controller.rb, app/views/items/edit.html.haml, app/views/items/show.html.haml, config/routes.rb
editアクションの追加
ビューファイルにif文追加
商品詳細画面で商品出品者かそうでない場合に表示を変更させるための記述
=> Item details

app/assets/javascripts/asearch.js, app/assets/stylesheets/search.scss, app/controllers/category_controller.rb, app/views/category/show.html.haml, config/routes.rb
#WHAT
カテゴリー検索機能の実装
ユーザーが選択したカテゴリーの商品を一覧表示
#WHY
ユーザーが見たいカテゴリーを絞り込んで一覧表示するため
https://gyazo.com/4e0154db00fdc5e83434e5fae600574b
=> [WIP]カテゴリー検索機能

app/controllers/items_controller.rb, app/controllers/purchase_controller.rb, app/models/item.rb, app/views/items/show.html.haml, config/routes.rb
商品の削除機能の追加
商品削除機能を追加することにより、出品ミスや、取引をやめたい場合に取り下げることができるようにするため。
=> [WIP]商品削除機能

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/card_controller.rb, app/controllers/items_controller.rb, app/models/category.rb, app/models/item.rb, app/models/item_image.rb, config/initializers/carrierwave.rb, spec/controllers/card_controller_spec.rb, spec/factories/brands.rb, spec/factories/items.rb, spec/factories/users.rb, spec/models/item_spec.rb, spec/models/user_spec.rb
+ factory_bot_rails の導入
+ バリテーションが間違いなくかかるか検証
テストコードの記載を短くするためユーザーなどのテンプレートを作成する。
=> [WIP]商品投稿機能のモデルの単体テスト

Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/category.js, app/assets/stylesheets/items.scss, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/brand_search.json.jbuilder, app/views/items/new.html.haml, app/views/layouts/application.html.haml, config/routes.rb, db/seeds.rb
+ ブランドの初期データの作成
+ ブランドをインクリメンタルサーチ機能で検索する機能の作成
+ ブランドをseedファイルで初期データを作ることにより、サーバー再起動の度に再作成しなくて良くなる。
+ ブランドをインクリメンタルサーチで検索することができる。
=> [WIP]ブランドのインクリメンタルサーチ機能

app/assets/stylesheets/application.scss, app/assets/stylesheets/identification.scss, app/assets/stylesheets/reset.scss, app/controllers/items_controller.rb, app/controllers/users_controller.rb, app/views/users/_list.html.haml, app/views/users/identification.html.haml, config/routes.rb
+ 本人確認ページのマークアップ
+ 本人確認ページの編集機能
+ リセットcssの導入
+ アドレスの情報を編集するため。
+ どのブラウザでもビュー崩れが起きないようにするため。
=> [WIP]本人確認ページのマークアップ

app/controllers/application_controller.rb, app/views/items/_header.html.haml
カテゴリーサーチのインスタンス変数名を@parentから@js_parentに変更
=> インスタンス変数名がかぶっていたので、修正

app/assets/stylesheets/mypage.scss, app/assets/stylesheets/users.scss, app/controllers/application_controller.rb, app/views/card/new.html.haml, app/views/card/show.html.haml, app/views/items/_header.html.haml, app/views/users/identification.html.haml, config/breadcrumbs.rb
マイページのビューの微調整（横幅が小さい時の表示を調整）
カード情報、本人情報のパンくずリストを追加
=> ビューの微調整とパンくずリスト

app/assets/stylesheets/buy_confirmation.scss, app/assets/stylesheets/credit.scss, app/assets/stylesheets/logout.scss, app/assets/stylesheets/toppage.scss, app/assets/stylesheets/users.scss, app/views/card/new.html.haml, app/views/users/_list.html.haml
viewの調整
少しずれているところがあったため調整
少しマージンを取ったところもあります
=> viewファイルの微調整

app/assets/javascripts/slider.js, app/assets/stylesheets/toppage.scss, app/views/card/new.html.haml, app/views/items/index.html.haml
トップページにスライドショーを追加
本家でもスライドショーを実装しているため。
=> スライドショーの実装

app/assets/stylesheets/breadcrumbs.scss, app/views/category/show.html.haml, app/views/items/search.html.haml, config/breadcrumbs.rb
=> パンくずリストの追加

app/views/category/show.html.haml, app/views/items/search.html.haml
カテゴリー検索、キーワード検索で表示される画像にもsoloutアイコンを追加しました
=> サーチページにsoldoutアイコンを追加

app/assets/javascripts/items_image_new.js, app/assets/stylesheets/items.scss, app/controllers/items_controller.rb, app/views/items/edit.html.haml
+ 商品の編集機能の追加。
+ imageの画像の初期データが入らない問題を解決。
+ imageの削除機能の実装
+ 商品で変更したい点を編集できるようにするため。
+ 商品編集ページに入った際にプレビューができてなかった問題を解決。
+ 出品時に登録した画像データを削除できなかったため。
=> [WIP]商品の編集機能
